// <auto-generated />
namespace StudentSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201908120313411_addgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
